version: 2

sources:
  - name: new_york_taxi_trips
    database: bigquery-public-data
    schema: new_york_taxi_trips
    tables:
      - name: tlc_yellow_trips_2019
      - name: taxi_zone_geom
      